package thinking_test

import (
	"testing"

	"github.com/router-for-me/CLIProxyAPI/v7/internal/registry"
	"github.com/router-for-me/CLIProxyAPI/v7/internal/thinking"
	_ "github.com/router-for-me/CLIProxyAPI/v7/internal/thinking/provider/codex"
	"github.com/tidwall/gjson"
)

func TestParseSuffixForModel_HyphenThinkingLevel(t *testing.T) {
	reg := registry.GetGlobalRegistry()
	reg.RegisterClient("thinking-hyphen-test", "codex", []*registry.ModelInfo{
		{ID: "test-reasoning", Thinking: &registry.ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}}},
	})
	t.Cleanup(func() { reg.UnregisterClient("thinking-hyphen-test") })

	got := thinking.ParseSuffixForModel("test-reasoning-high", "codex")
	if !got.HasSuffix || got.ModelName != "test-reasoning" || got.RawSuffix != "high" {
		t.Fatalf("ParseSuffixForModel() = %#v", got)
	}
}

func TestParseSuffixForModel_ExactHyphenModelWins(t *testing.T) {
	reg := registry.GetGlobalRegistry()
	reg.RegisterClient("thinking-exact-hyphen-test", "codex", []*registry.ModelInfo{
		{ID: "foo-high", Thinking: &registry.ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}}},
	})
	t.Cleanup(func() { reg.UnregisterClient("thinking-exact-hyphen-test") })

	got := thinking.ParseSuffixForModel("foo-high", "codex")
	if got.HasSuffix || got.ModelName != "foo-high" {
		t.Fatalf("exact model should not be parsed as suffix, got %#v", got)
	}
}

func TestParseSuffixForModel_AutoGeneratedThinkingAlias(t *testing.T) {
	reg := registry.GetGlobalRegistry()
	support := &registry.ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}}
	reg.RegisterClient("thinking-auto-alias-test", "codex", []*registry.ModelInfo{
		{ID: "foo", Thinking: support},
		{ID: "foo-high", Thinking: support, ThinkingAliasBase: "foo"},
	})
	t.Cleanup(func() { reg.UnregisterClient("thinking-auto-alias-test") })

	got := thinking.ParseSuffixForModel("foo-high", "codex")
	if !got.HasSuffix || got.ModelName != "foo" || got.RawSuffix != "high" {
		t.Fatalf("auto alias should parse to base+level, got %#v", got)
	}
}

func TestApplyThinking_CodexHyphenSuffixSetsReasoningEffort(t *testing.T) {
	reg := registry.GetGlobalRegistry()
	support := &registry.ThinkingSupport{Levels: []string{"low", "medium", "high", "xhigh"}}
	reg.RegisterClient("thinking-apply-alias-test", "codex", []*registry.ModelInfo{
		{ID: "test-reasoning", Thinking: support},
		{ID: "test-reasoning-high", Thinking: support, ThinkingAliasBase: "test-reasoning"},
	})
	t.Cleanup(func() { reg.UnregisterClient("thinking-apply-alias-test") })

	body := []byte(`{"model":"test-reasoning","reasoning":{"effort":"medium"}}`)
	out, err := thinking.ApplyThinking(body, "test-reasoning-high", "openai", "codex", "codex")
	if err != nil {
		t.Fatalf("ApplyThinking() error = %v", err)
	}
	if got := gjson.GetBytes(out, "reasoning.effort").String(); got != "high" {
		t.Fatalf("reasoning.effort = %q, want high, body=%s", got, string(out))
	}
}
